name: skarnik_database_generator
description: A command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.1.2 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.1.1
  objectbox_generator: any
  test: ^1.24.6
dependencies:
  dio: ^5.3.3
  html: ^0.15.4
  objectbox: ^2.3.0
  rxdart: ^0.27.7
